Add manual+auto /restart feature, remove hardcoded userid
Poryaei/NotCoin-Clicker pull request #27
Opened 2024-03-09 21:58 UTC by d8rt8v

**Add manual bot restart feature and clean up hardcoded Telegram ID**

- Implement manual restart functionality for the bot via Telegram
- Automatically restart the bot upon encountering errors
- Remove hardcoded Telegram ID from the script for flexibility

Nice bot btw!

2024-03-17 21:45 UTC, IgorGradov commented on clicker.py
> +        os.execv(sys.executable, ['python3', script_path] + sys.argv)
Can be python and python3.11 and python 3.12 as well

2024-03-18 17:47 UTC, d8rt8v commented
@Poryaei can you review my PR?

2024-03-20 21:59 UTC, IgorGradov commented
You've just removed some of the functionality.....

2024-03-20 22:13 UTC, IgorGradov requested changes

2024-03-20 22:13 UTC, IgorGradov commented on clicker.py
> -    if not user_id in [admin, 6583452530]:
By removing this line, you allow anyone to control your bot.

2024-03-20 22:13 UTC, IgorGradov commented on clicker.py
> -    elif user_id == 6583452530 and 'balance' in db and db['balance']:
you removed the balance parsing here

2024-03-20 22:13 UTC, IgorGradov commented on clicker.py
> +        os.execv(sys.executable, ['python3', script_path] + sys.argv)
there is no guarantee that the right python interpreter will be called as python3

2024-03-20 22:13 UTC, IgorGradov commented on clicker.py
> +                    error_start_time = time.time()
you don't reset the timer if he manages keep mining

2024-03-20 22:13 UTC, IgorGradov commented on clicker.py
> +                    os.execv(sys.executable, ['python3', script_path] + sys.argv)
duplicated line with line 503

2024-03-25 21:34 UTC, Poryaei commented
Thank you for the effort you put in!
But the code you wrote has some issues! and it causes disruption, as our friend @IgorGradov mentioned.
Unfortunately, the pull request is not being accepted.

2024-03-25 21:34 UTC, closed without merging

2024-03-25 21:42 UTC, Poryaei commented on clicker.py
> -    if not user_id in [admin, 6583452530]:
6583452530

It's @notcoin_bot user id

2024-03-25 21:45 UTC, Poryaei commented on clicker.py
> +        os.execv(sys.executable, ['python3', script_path] + sys.argv)
I think this restart will run into trouble! Before that, the bot should be stopped
await client.disconnect()

#clicker ... stop